#Number of orders: 2
#Number of shipments: 2
#Insufficiently many products: No
#Flipped products: Yes
#In-process order update: No
#Dropped products: No
#In-process order interruption: Yes
#Part flipping: Yes
#Faulty products: No
#Moving obstacles: 2
#Sensor blackout: No
#2 arms advantageous: Yes
#Time limit: No

options:
  insert_models_over_bins: true
  insert_models_over_shelves: true
  belt_population_cycles: 0
  model_type_aliases:
    order_part1: pulley_part_red
    order_part2: gear_part_blue
    order_part3: gasket_part_red
    order_part4: gear_part_red

shelf_layout:
  row_1: ['base','collar',0,'base'] #shelves: 3, 4, 5
  row_2: ['pipe', 0,'base','base']   #shelves: 6, 7, 8
  row_3: ['base','pipe',0,'collar'] #shelves: 9, 10, 11

aisle_layout:
  person_1:
    location: -1.57
    start_time: 0.
    move_time: 9.
    wait_time: 7.
  person_2:
    location: 4.57
    start_time: 16.
    move_time: 9.
    wait_time: 7.

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 1
    destinations: [agv1]
    products:
      part_0:
        type: order_part1
        pose:
          xyz: [0.1, -0.2, 0]
          rpy: ['pi', 0, 0]
      part_1:
        type: order_part4
        pose:
          xyz: [-0.1, -0.2, 0]
          rpy: [0, 0, 0]
      part_2:
        type: order_part3
        pose:
          xyz: [0.15, 0.15, 0]
          rpy: [0, 0, 0]
  order_1:
    announcement_condition: unwanted_products
    announcement_condition_value: 2
    shipment_count: 1
    destinations: [agv2]
    products:
      part_0:
        type: order_part2
        pose:
          xyz: [0.1, -0.2, 0]
          rpy: [0, 0, 0]
      part_1:
        type: order_part2
        pose:
          xyz: [-0.1, -0.2, 0]
          rpy: [0, 0, 0]

models_over_bins:
  bin3:
    models:
      pulley_part_red:
        xyz_start: [0.2, 0.2, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 2
  bin5:
    models:
      gear_part_red:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.5, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 3
        num_models_y: 3

#2 arms advantageous
models_over_shelves:
  shelf8:
    models:
      gear_part_blue:
        xyz_start: [0.7, -0.5, 0.0]
        xyz_end: [0., -0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 5
        num_models_y: 2
  shelf11:
    models:
      gasket_part_red:
        xyz_start: [0.7, 0.5, 0.0]
        xyz_end: [0., 0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 4
        num_models_y: 1

time_limit: -1
