#Number of orders: 1
#Number of shipments: 1
#Insufficiently many products: No
#Flipped products: No
#In-process order update: Yes
#Dropped products: No
#In-process order interruption: No
#Part flipping: No
#Faulty products: Yes
#Moving obstacles: No
#Sensor blackout: No
#2 arms advantageous: Yes
#Time limit: No
options:
  insert_models_over_bins: true
  insert_models_over_shelves: true
  spawn_extra_models: false
  model_type_aliases:
    order_part1: pulley_part_green
    order_part2: gear_part_green
    order_part3: gear_part_red

shelf_layout:
  row_1: ['base',0,'collar','base'] #shelves: 3, 4, 5
  row_2: ['pipe', 0,'base','base']   #shelves: 6, 7, 8
  row_3: ['base','pipe',0,'collar'] #shelves: 9, 10, 11

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 1
    destinations: [any]
    products:
      part_0:
        type: order_part1
        pose:
          xyz: [-0.1, -0.2, 0]
          rpy: [0, 0, 0]
      part_1:
        type: order_part2
        pose:
          xyz: [-0.1, 0, 0]
          rpy: [0, 0, 'pi']
      part_2:
        type: order_part3
        pose:
          xyz: [-0.1, 0.15, 0]
          rpy: [0, 0, 0]
  order_0_update_0:
    announcement_condition: wanted_products
    announcement_condition_value: 2
    shipment_count: 1
    destinations: [any]
    products:
      part_0:
        type: order_part1
        pose:
          xyz: [0.1, -0.2, 0]
          rpy: [0, 0, 0]
      part_1:
        type: order_part3
        pose:
          xyz: [0.0, 0.15, 0]
          rpy: [0, 0, 0]

models_over_bins:
   bin3:
     models:
       pulley_part_green:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: [0, 0, 0]
         num_models_x: 2
         num_models_y: 2
   bin5:
     models:
       gear_part_red:
         xyz_start: [0.1, 0.1, 0.0]
         xyz_end: [0.5, 0.5, 0.0]
         rpy: [0, 0, 0]
         num_models_x: 3
         num_models_y: 3
models_over_shelves:
  shelf8:
    models:
      gear_part_green:
        xyz_start: [0.7, -0.5, 0.0]
        xyz_end: [0., -0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 5
        num_models_y: 2
  shelf11:
    models:
      gear_part_red:
        xyz_start: [0.7, 0.5, 0.0]
        xyz_end: [0., 0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 5
        num_models_y: 2
faulty_products:
  - gear_part_red_5

time_limit: -1
