# Baseline3
#drop parts: no
#High priority orders: no
#Part flipping: yes
#Faulty parts: yes
#Dynamic obstacles: no
#Sensor blackout: no
#2 arms advantageous: yes
options:
  insert_models_over_bins: true
  insert_models_over_shelves: true
  spawn_extra_models: false

shelf_layout:
  row_1: ['base',0,'collar','base'] #shelves: 3, 4, 5
  row_2: ['pipe', 0,'base','base']   #shelves: 6, 7, 8
  row_3: ['base','pipe',0,'collar'] #shelves: 9, 10, 11

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 2
    destinations: [agv1, agv2]
    products:
      part_0:
        type: pulley_part_green
        pose:
          xyz: [-0.1, -0.2, 0]
          rpy: ['pi', 0, 0]
      part_1:
        type: gear_part_green
        pose:
          xyz: [-0.1, 0, 0]
          rpy: [0, 0, 'pi']
      part_2:
        type: gear_part_red
        pose:
          xyz: [-0.1, 0.15, 0]
          rpy: [0, 0, 0]

models_over_bins:
   bin3:
     models:
       pulley_part_green:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: [0, 0, 0]
         num_models_x: 2
         num_models_y: 2
   bin5:
     models:
       gear_part_red:
         xyz_start: [0.1, 0.1, 0.0]
         xyz_end: [0.5, 0.5, 0.0]
         rpy: [0, 0, 0]
         num_models_x: 3
         num_models_y: 3
models_over_shelves:
  shelf8:
    models:
      gear_part_green:
        xyz_start: [0.7, -0.5, 0.0]
        xyz_end: [0., -0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 5
        num_models_y: 2
  shelf11:
    models:
      gear_part_red:
        xyz_start: [0.7, 0.5, 0.0]
        xyz_end: [0., 0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 5
        num_models_y: 2
faulty_products:
  - gear_part_red_5

#time_limit: -1
