sensors:
  # 17 logical sensors
  logical_camera_0: #opp back shelf r
    type: logical_camera
    pose:
      xyz: [ 4.95, 3.66, 2.49 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]

  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [ 5, 1.750927, 1.82 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]

  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [ 5, -1.76, 1.82 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]

  logical_camera_3: #back shelf r
    type: logical_camera
    pose:
      xyz: [ 4.95, -3.55, 2.49 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]

  logical_camera_4: #opp back shelf r
    type: logical_camera
    pose:
      xyz: [ 3.05, 3.66, 2.49 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]


  logical_camera_5: #bin 1
    type: logical_camera
    pose:
      xyz: [3.082385, 1.750927, 1.82]
      rpy: [0, 'pi/2', 0]

  logical_camera_6: #bin 1
    type: logical_camera
    pose:
      xyz: [3.082385, -1.750927, 1.82]
      rpy: [0, 'pi/2', 0]

  logical_camera_7: #back shelf l
    type: logical_camera
    pose:
      xyz: [ 3.05, -3.55, 2.49 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]

  logical_camera_8: #bin2
    type: logical_camera
    pose:
      xyz: [ 0, 7.46, 1.82 ]
      rpy: [ 0, 'pi/2', 0 ]

  logical_camera_9: # conveyor
    type: logical_camera
    pose:
      xyz: [ -0.14, -1.82, 1.96 ]
      rpy: [ 0, 'pi/2', 0 ]

  logical_camera_10: #bin1
    type: logical_camera
    pose:
      xyz: [0, -7.46, 1.82]
      rpy: [0, 'pi/2', 0]

  logical_camera_11: #front shelf l
    type: logical_camera
    pose:
      xyz: [ -13.54, 3.01, 2.49 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]

  logical_camera_12: #middle shelf r
    type: logical_camera
    pose:
      xyz: [ -13.54, 0, 2.49 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]

  logical_camera_13: #back shelf l
    type: logical_camera
    pose:
      xyz: [ -13.54, -3.01, 2.49 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]

  logical_camera_14: #front shelf r
    type: logical_camera
    pose:
      xyz: [ -15.44, 3.01, 2.49 ]
      rpy: [ 0, 'pi/2', 'pi/2' ]

  logical_camera_15: # middle shelf l over shelf
    type: logical_camera
    pose:
      xyz: [-3.25 - 6*2.04, 0, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_16: #back shelf r
    type: logical_camera
    pose:
      xyz: [-15.44, -3.01, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  laser_profiler_0:
    type: laser_profiler
    pose:
      xyz: [ 0., 1.486, 1.526 ]
      rpy: [ 'pi/2', 'pi/2', 0 ]

  range_finder_0:
    type: proximity_sensor
    pose:
      xyz: [ 0, 2.840000, 0.970000 ]
      rpy: [ 1.570796, 0.524365, 1.570796 ]

  breakbeam_0:
    type: break_beam
    pose:
      xyz: [ -0.004795, 4.492549, 0.879306 ]
      rpy: [ 0, 0, -1.557900 ]

  breakbeam_1:
    type: break_beam
    pose:
      xyz: [ 0.184308, -0.501289, 0.879306 ]
      rpy: [ 0, 0, 1.906282 ]

  shelf_breakbeam_0:
    type: break_beam
    pose:
      #xyz: [ -2.177333, 2.359924, 0.438050 ]
      xyz: [ -1.679531, 2.359924, 0.438050 ]
      rpy: [ 0, 0, -1.57 ]

  shelf_breakbeam_1:
    type: break_beam
    pose:
      xyz: [ -6.020965, 2.364526, 0.438050 ]
      rpy: [ 0, 0, -1.57 ]

  shelf_breakbeam_2:
    type: break_beam
    pose:
      xyz: [ -12.607288, 2.301808, 0.438050 ]
      rpy: [ 0, 0, -1.57 ]

  shelf_breakbeam_3:
    type: break_beam
    pose:
      xyz: [ -16.405857, 2.343718, 0.438050 ]
      rpy: [ 0, 0, -1.57 ]

  shelf_breakbeam_4:
    type: break_beam
    pose:
#      xyz: [ -2.255234, -0.742663, 0.438050 ]
#      xyz: [ -2.181771, -0.742604, 0.438050 ]
#      xyz: [ -1.753632, -0.742263, 0.438050 ]
#      xyz: [ -1.590664, -0.742133, 0.438050 ]
#      xyz: [ -2.720428, -0.743033, 0.438050 ]
#      xyz: [ -2.292360, -0.742692, 0.438050 ]
#      xyz: [ -2.408548, -0.742785, 0.438050 ]
      xyz: [ -1.577878, -0.742123, 0.438050 ]
      #xyz: [ -1.679531, -0.742663, 0.438050 ]
      #xyz: [ -1.574, -0.742663, 0.438050 ]
      rpy: [ 0, 0, -1.57 ]

  shelf_breakbeam_5:
    type: break_beam
    pose:
      xyz: [ -6.011172, -0.715403, 0.438050 ]
      rpy: [ 0, 0, -1.57 ]


  shelf_breakbeam_6:
    type: break_beam
    pose:
      xyz: [ -12.592617, -0.728178, 0.438050 ]
      rpy: [ 0, 0, -1.57 ]


  shelf_breakbeam_7:
    type: break_beam
    pose:
#      xyz: [ -16.447124, -0.740479, 0.438050 ]
#      xyz: [ -16.746405, -0.740717, 0.740717 ]
#      xyz: [ -16.589651, -0.740592, 0.740717 ]
#      xyz: [ -15.969187, -0.740098, 0.740717 ]
#      xyz: [ -16.331347, -0.740386, 0.740717 ]
#      xyz: [ -16.221481, -0.740299, 0.740717 ]
      xyz: [ -16.793615, -0.740755, 0.740717 ]
      #xyz: [ -16.648241, -0.740479, 0.438050 ]
      rpy: [ 0, 0, -1.57 ]





