# RWA4
#drop parts: no
#new order: no
#flipped part: yes
#faulty parts: yes
#faulty gripper: no
#moving obstacles: yes (2: aisles 2 and 3)
#sensor blackout: yes

time_limit: 500

options:
  gazebo_state_logging: true
  insert_models_over_bins: true
  insert_models_over_shelves: true
  belt_population_cycles: 0
  model_type_aliases:
    order_part1: gasket_part_red
    order_part2: gear_part_blue

shelf_layout:
  row_1: ['base','collar',0,'base'] #shelves: 3, 4, 5
  row_2: ['pipe', 0,'base','base']   #shelves: 6, 7, 8
  row_3: ['base','pipe',0,'collar'] #shelves: 9, 10, 11


orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 1
    destinations: [agv1]
    products:
      part_0:
        type: gasket_part_red
        pose:
          xyz: [0.15, -0.2, 0]
          rpy: [0, 0, '-pi/4']
      part_1:
        type: gasket_part_red
        pose:
          xyz: [-0.15, -0.2, 0]
          rpy: [0, 0, '-pi/4']
      part_2:
        type: gear_part_blue
        pose:
          xyz: [-0.15, 0.2, 0]
          rpy: [0, 0, 0]

models_over_bins:
  bin3:
    models:
      gear_part_blue:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.5, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 3
        num_models_y: 3

models_over_shelves:
  shelf1:
    models:
      gasket_part_red:
        xyz_start: [1, 0.4, 0.0]
        xyz_end: [0., 0.4, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 6
        num_models_y: 1
